import { useState, useEffect } from 'react'
import type { Metadata, Viewport } from 'next'
import Head from 'next/head'

import './globals.css'
import { Navbar , Footer } from '@/components'


export const metadata: Metadata = {
  title: '享樂酒店',
  description: 'Generated by create next app',
}
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1
}

const navigation = [
  { name: 'Dashboard', href: '#', current: true },
  { name: 'Team', href: '#', current: false },
  { name: 'Projects', href: '#', current: false },
  { name: 'Calendar', href: '#', current: false },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
